version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "strickvl"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "strickvl"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
    groups:
      cargo-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      cargo-major:
        patterns:
          - "*"
        update-types:
          - "major"
