version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "strickvl"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
      - "ci"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "strickvl"
    commit-message:
      prefix: chore
      include: scope
    labels:
      - "dependencies"
